# Generated by Django 4.1.2 on 2022-10-27 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_carousel_alter_page_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='created_at',
            new_name='createt_at',
        ),
        migrations.AddField(
            model_name='carousel',
            name='createt_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
